apiVersion: apps/v1
kind: Deployment
metadata:
  name: iris-model-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: iris-model
  template:
    metadata:
      labels:
        app: iris-model
    spec:
      containers:
      - name: iris-model-container
      ### iam not sure if this is correct, but I am trying to deploy a FastAPI app with Docker
        image: adelsaleh/iris-fastapi-app:latest  # Replace with your Docker Hub image!
        ports:
        - containerPort: 80
